
// Pipeline 101

stage ('Build') {
    node ('maven') {
        echo "Building"
        // Check-out code
        git credentialsId: 'github-pmdevel', url: 'https://github.com/pmdevel/jenkins2-demo-source-webapp.git'

        // Let Maven help you to create a "release" version. Use BUILD_NUMBER from Jenkins
        sh 'mvn build-helper:parse-version versions:set -DnewVersion=\\${parsedVersion.majorVersion}.\\${parsedVersion.minorVersion}.$BUILD_NUMBER versions:commit '

        // Get version from pom
        def pom = readMavenPom file: 'pom.xml'
        writeFile file: "version.properties", text: "version=${pom.version}"

        sh 'cat version.properties'
        // Failure will abort with currentBuild.result: 'FAILURE'
        sh "mvn -B clean compile "

        stash includes: "version.properties, target/**/*", name: "build"
    }
}

stage ('JUnit Test') {
    node ('maven') {
        echo "Testing"
        // Do not recompile
        unstash "build"
        // Failure will abort with currentBuild.result: 'UNSTABLE'
        // -Dfail.junit.tests=true
        sh "mvn -B test || exit 0 "
        step([$class: 'JUnitResultArchiver', testResults: '**/surefire-reports/TEST-*.xml'])
    }
}

stage ('Dockerize') {
    node ('maven') {
        unstash "build"
        sh "mvn -B package docker:build -DskipTests"
    }

}


stage ('Deploy') {
    node ('maven') {
        unstash "build"
        def containerName = 'pmdevel/codenite-demo-app'
        def containerAlias = 'demo-app-101'
        // Get version created in previous stage (build)
        def props = readProperties file: 'version.properties'
        def containerVersion = props.version
        def containerPort = 8888
        def profile = "default"
        def javaOpts = "-e JAVA_OPTS=-Dspring.profiles.active=${profile}"
        // Stop existing container (if any), ignore bad exit code...
        sh "docker stop ${containerAlias} || exit 0"
        echo "Starting ${containerName}"
        sh "docker run --rm  --name ${containerAlias} -d -p ${containerPort}:9090 ${javaOpts} ${containerName}:${containerVersion}"
        echo "${containerName} with alias ${containerAlias} started, listening on port ${containerPort}..."
        echo "Access it on http://localhost:${containerPort}"
    }

}
