#!/usr/bin/env groovy

// Pipeline manual step

@NonCPS
def setDisplay(String displayName, String description) {
    def build = currentBuild.rawBuild
    // rawBuild returns a Run object
    // http://javadoc.jenkins-ci.org/hudson/model/Run.html
    // With a lot off Juicy stuff :-)
    build.displayName = "#${build.number}, ${displayName}"
    if (description != null && !description.isEmpty()) {
        build.description = description
    }

}

def waitForManualApproval(def messageText, def buttonText) {
    def userInput = ""

    try {
        timeout(time: 30, unit: 'SECONDS') {
            userInput = input(
                    id: 'deploymentConfirmation', vale: 'continue', message: messageText, ok: buttonText,
                    submitter: 'jenkins', submitterParameter: 'deploymentApprovedBy'
            )
        }
    } catch (fie) {
        echo ("Error: ${fie}")
        setDisplay("Deploy Aborted", null)
        throw fie
    } finally {
        echo ("User input: ${userInput}")
    }
    setDisplay("Deploy Confirmed", "By user: ${userInput}")

    return userInput
}


stage ('Stage One') {
    node ('maven') {
        echo "In first stage"
    }
}


stage ('Deploy to PRODUCTION') {

    waitForManualApproval("Deploy in PRODUCTION?", "Deploy")

    node ('maven') {

        echo "Deploying to PRODUCTION"
    }

}
