#!/usr/bin/env groovy

// Pipeline manual step

def waitForManualApproval(def messageText, def buttonText) {
    def userInput = ""

    try {
        timeout(time: 30, unit: 'SECONDS') {
            userInput = input(
                    id: 'deploymentConfirmation', vale: 'continue', message: messageText, ok: buttonText,
                    submitter: 'jenkins', submitterParameter: 'deploymentApprovedBy'
            )
        }
    } finally {
        echo ("User input: ${userInput}")
    }

    return userInput
}


stage ('Stage One') {
    node ('maven') {
        echo "In first stage"
    }
}


stage ('Deploy to PRODUCTION') {

    waitForManualApproval("Deploy in PRODUCTION?", "Deploy")

    node ('maven') {

        echo "Deploying to PRODUCTION"
    }

}
